extends: default

rules:
  indentation: disable
  comments-indentation: disable
  trailing-spaces: disable
  line-length: disable
  colons:
    level: warning
  empty-lines:
    level: warning
  empty-values:
    level: warning